dev:
  EMPLOYEES_TABLE: honeydew-employee-service-table-dev
  ENVIRONMENT: DEV
test:
  EMPLOYEES_TABLE: honeydew-employee-service-table-test
  ENVIRONMENT: TEST
prod:
  EMPLOYEES_TABLE: honeydew-employee-service-table-prod
  ENVIRONMENT: PRODUCTION
